/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernorContract__factory } from "./GovernorContract__factory";
export { Timelock__factory } from "./Timelock__factory";
